### ISSUE TITLE
Find function errors

### ISSUE THREAD

**Issue by MalekBezzina** [erdogant/clustimage#10]
Hello,

The find function has stopped working, In fact if i use the "pca" i get this error:
![image](https://user-images.githubusercontent.com/57270244/193683287-ed8d0c31-1060-4998-9f47-cfa47ca6b563.png)

If i use "hog" i get another type of error.
![image](https://user-images.githubusercontent.com/57270244/193681805-5843869f-8dd6-420a-aafd-b8b7d406c56d.png)

It was working before and i didn't change anything! could you please help me resolve the problem.

**Comment by erdogant** [comment]
Thanks for mentioning this. I will look into this. Maybe a dependent package got an update(?)

**Comment by MalekBezzina** [comment]
Thank you this problem has been solved!
