### ISSUE TITLE
Define number of clusters manually

### ISSUE THREAD

**Issue by zeppehpt1** [erdogant/clustimage#17]
Hello,
is it possible to define the exact number of clusters upfront?
I tried setting the min and max cluster to the same value but this didn't solved the issue.

**Comment by erdogant** [comment]
I added this functionality. Update to latest version with: `pip install -U clustimage`
You need to set min_clust and max_clust the same.

Feel free to <a href='https://www.buymeacoffee.com/erdogant' target='_blank'><img height='36' style='border:0px;height:36px;' src='https://cdn.ko-fi.com/cdn/kofi1.png?v=3' border='0' alt='Buy Me a Coffee at ko-fi.com' /></a>
