### ISSUE TITLE
Clustimage.find() and new images

### ISSUE THREAD

**Issue by dt99jay** [erdogant/clustimage#23]
Can I check that I'm using `Clustimage.find()` correctly? I'm passing it the filename of a new image, not the index of one already contained in the cl object (the docs seem to show an image from X being passed to `find()`). Was hoping it would show a shorter distance between the new input and the images in the bottom left and bottom right.

![image](https://github.com/erdogant/clustimage/assets/1680023/d585ef1f-0736-4a10-baa5-a0286c9640dc)

Thanks for publishing this library!

**Comment by dt99jay** [comment]
Have since tried PCA which is giving me much better results for previously unseen images, so will close this.

**Comment by erdogant** [comment]
Happy to hear that you find a solution!
