### ISSUE TITLE
Wrong distance metric used with hash features?

### ISSUE THREAD

**Issue by dlindenkreuz** [erdogant/clustimage#24]
As far as I know, the euclidean distance metric does not make sense for comparing hashes as features. One would use the hamming distance instead.

However, the examples show pHash in combination with euclidean. Is this intended or did I miss something?

**Comment by erdogant** [comment]
The default method for clustimage is set to PCA. When using hashes, it is wise to also think about the distance metric. Hamming distance would be a better choice. Where did you see this example?

**Comment by dlindenkreuz** [comment]
I can't find it anymore. Must have been some blog post or Gist. My bad! Closing.
