### ISSUE TITLE
Question on CNN

### ISSUE THREAD

**Issue by karelin** [erdogant/clustimage#3]
Is it possible to use pre-trained neural network (for example, based on ImageNet) for image features in `clustimage`?
And do you support using U-MAP for dimension reduction?

**Comment by erdogant** [comment]
Using pre-trained classifiers such as ImageNet is not yet supported. But this is a good suggestion.
UMAP is now available in clustimage. 

update with 
`pip install -U clustimage
`
```
from clustimage import Clustimage
# Initialize
cl = Clustimage(embedding='umap')
# load example data
Xraw = cl.import_example(data='mnist')
# Import data in a standardized manner
X = cl.import_data(Xraw)
# Extract features
Xfeat = cl.extract_feat(X)
# Embedding
xycoord = cl.embedding(Xfeat)
# Scatter
cl.scatter()
cl.scatter(zoom=None, img_mean=False, dotsize=20, text=False, plt_all=True)

```
