### ISSUE TITLE
Trying to retrieve original file path names in the results

### ISSUE THREAD

**Issue by Sid01123** [erdogant/clustimage#4]
Is there a way to be able to get the original pathnames of images used post fit_transform?

I am uploading images onto google colab, and reading them in by their filepaths as "/content/name_of_image", and then I wish to be able to recover this "/content/name_of_image" post running clustering.

I tried to extract pathnames per label using the following code, but seemed to be getting the filepaths for images created in a temporary directory as follows:

CODE
Iloc = cl.results['labels']==0
cl.results['pathnames'][Iloc]

OUTPUT
array(['/tmp/clustimage/8732cb41-c72d-4266-b164-ff453d68428a.png',
       '/tmp/clustimage/440fecd8-8a9c-49a0-b100-ccfb66107425.png',
       '/tmp/clustimage/3c9c38d8-4da9-4e4f-9130-d3836182b8c6.png',
       '/tmp/clustimage/85cc4848-1faf-44ea-ae4c-9d9d88bd6323.png',
       '/tmp/clustimage/6127e4fb-1c25-4ba9-8d68-56ef482e3db4.png',
       '/tmp/clustimage/abcf85e0-af1a-48f1-8861-122122b64e32.png',
       '/tmp/clustimage/275bbde0-394d-4ba4-b4d0-1c67da323c8b.png',
       '/tmp/clustimage/30b62285-2628-45c0-86b2-fea305cb8db3.png',
       '/tmp/clustimage/c47a6867-3c8f-480c-a7bd-b3e7ec4ba334.png',
       '/tmp/clustimage/da5c17fc-de2a-4375-b03c-066a0904428a.png'], dtype='<U56')

I wish to get the output as the original filenames that were in the pathnames list.

**Comment by erdogant** [comment]
Can you show with an example how this occurs?
When I try the flowers example, it stores the filenames and paths correctly.
The unique identifiers are only used if a data matrix is given as an input.

```
from clustimage import Clustimage
cl = Clustimage(method='pca', embedding
g='umap')
# Import data
Xlist = cl.import_example(data='flowers')
# Import data in a standardized manner
X = cl.import_data(Xlist)

X.keys()
dict_keys(['img', 'feat', 'xycoord', 'pathnames', 'labels', 'url', 'filenames'])
print(X['filenames'][0:5])
# array(['0001.png', '0002.png', '0003.png', '0004.png', '0005.png'],


```

**Comment by Sid01123** [comment]
Dear Mr. Taskesen,

Thank you so much for taking the time to add this update. I shall try It
out and let you know!

Best,
Sid

**Comment by erdogant** [comment]
I am closing this one. Re-open this issue if required.
