### ISSUE TITLE
Transfer learning

### ISSUE THREAD

**Issue by MalekBezzina** [erdogant/clustimage#8]
Hello, is there a way to use the transfer learning technique with this model?
I would like to use it repeatedly with a cumulative dataset

**Comment by erdogant** [comment]
It is possible to store and load the model for later usage. See more information in [the docs](https://erdogant.github.io/clustimage/pages/html/Save%20and%20Load.html#loading).

But the results are unsupervised, and thus no labels are used in the modeling. Adding more data points would be as easy as re-running the model with the cumulative dataset. If you want to do a mapping of new unseen data points into the existing data space you can use the `find` functionality. I now added a whole section for this alone in the [documentation pages](https://erdogant.github.io/clustimage/pages/html/Find.html).

**Comment by MalekBezzina** [comment]
Hello, Thank you so much for you help and guidance, it is very much appreciated !
